'🧱 Componente':
- src/components/index.js
 
'🐛 Bug':
- any: ['src/components/*.vue']
  all: ['!src/stories/*']

'📃 Documentação':
- any: ['src/stories/*.stories.mdx']
  all: ['!src/components/index.js', '!src/components/*.vue']

'🛠️ Build':
- build/rollup.config.js
- src/entry.js

'🧩 Token':
- src/assets/sass/**/*
