'🧱 Componente':
- src/components/index.ts

'🐛 Bug':
- any: ['src/components/*.vue']
  all: ['!src/stories/**']

'📃 Documentação':
- any: ['src/stories/**/*.stories.mdx']
  all: ['!src/components/index.ts', '!src/components/*.vue']

'🛠️ Build':
- vite.config.ts
- src/components/index.ts
- .github/**/*

'🧩 Token':
- src/assets/sass/**/*
- src/stories/tokens/*.stories.mdx