name: "Publisher 🚀"

on:
    push:
        branches:
          - master

jobs:
    release:
        name: Publish 🚀
        runs-on: ubuntu-latest
        steps:
            - name: 📚 checkout
              uses: actions/checkout@v2.3.4
            - name: 🟢 node
              uses: actions/setup-node@v2.1.4
              with:
                  node-version: 12
                  registry-url: https://registry.npmjs.org
            - name: Publish 🚀
              run: npm run build && npm publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
