name: "Releaser ✔️"
on:
  push:
    branches:
      - main
      - v2.70-legacy

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          npm install -g conventional-changelog-cli@2.2.2
          npm install conventional-changelog-angular
      
      - name: Debug - List files
        run: ls -la


      - name: Debug - Check changelog.config.js
        run: cat changelog.config.js

      - name: Debug - Check git log
        run: git log -n 5 --pretty=format:"%h - %s (%cr) <%an>"

      - name: Generate changelog
        run: |
          touch CHANGELOG.md
          conventional-changelog -p angular -i CHANGELOG.md -s -r 0 --config changelog.config.js
        continue-on-error: true

      - name: Debug - Check CHANGELOG.md
        run: cat CHANGELOG.md

      - name: Set changelog to env
        run: |
          echo "CHANGELOG<<EOF" >> $GITHUB_ENV
          cat CHANGELOG.md >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Creates tag
        uses: Klemensas/action-autotag@stable
        id: auto-tag
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          tag_prefix: "v"

      - name: Read package.json
        uses: tyankatsu0105/read-package-version-actions@v1
        id: package-version

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.auto-tag.outputs.tagname }}
          release_name: "v${{ steps.package-version.outputs.version }}"
          body: |
            Mudanças nessa release: ${{ env.CHANGELOG }}
          draft: false
          prerelease: false
